### ISSUE TITLE
Dribbblish right click menu trims outside screen

### ISSUE THREAD

**Issue by itsrave** [morpheusthewhite/spicetify-themes#467]
**Describe the bug**
Dribbblish right click menu trims outside screen (seen in playlist list, and when clicked on user icon in right left corner)

**To Reproduce**
1. Go to Spotify
2. Right click on playlist (f.e. last playlist visible in side menu)

**Expected behavior**
Menus are not trimmed.

**Screenshots**
![image](https://user-images.githubusercontent.com/28827494/125827313-9eec9897-7766-4830-9a0a-34a6ab373871.png)

**Logs**
```console
Uncaught (in promise) TransportError: Cannot authenticate disconnected transport.
    at U._authenticate (https://xpui.app.spotify.com/vendor~xpui.js:29:1628327)
    at U.authenticate (https://xpui.app.spotify.com/vendor~xpui.js:29:1635746)
    at e.request (https://xpui.app.spotify.com/vendor~xpui.js:29:1541155)
    at e.resolveConfig (https://xpui.app.spotify.com/vendor~xpui.js:29:1538987)
    at t.<anonymous> (https://xpui.app.spotify.com/vendor~xpui.js:29:1553077)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:1549890
    at Object.next (https://xpui.app.spotify.com/vendor~xpui.js:29:1549995)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:1548930
    at new Promise (<anonymous>)
    at Oe (https://xpui.app.spotify.com/vendor~xpui.js:29:1548675)
spicetifyWrapper.js:821 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
vendor~xpui.js:29 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at u (https://xpui.app.spotify.com/vendor~xpui.js:29:2078243)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2080827)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:1527849
    at Ia (https://xpui.app.spotify.com/vendor~xpui.js:29:2362662)
    at Ps (https://xpui.app.spotify.com/vendor~xpui.js:29:2386514)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2572645)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2332170)
    at Rs (https://xpui.app.spotify.com/vendor~xpui.js:29:2386293)
    at Ts (https://xpui.app.spotify.com/vendor~xpui.js:29:2371064)
    at gs (https://xpui.app.spotify.com/vendor~xpui.js:29:2369986)
vendor~xpui.js:29 [transport.transport] Auth header setting awaiting authentication.
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
4
vendor~xpui.js:29 [transport.transport] Auth header setting awaiting authentication.
5
vendor~xpui.js:29 [transport.transport] Auth header set after authentication.
```

**Specifics:**
 - OS: Arch Linux /w KDE Plasma
 - Spotify version: 1.1.56.595.g2d2da0de
 - Spicetify version 2.5.0-1
 - Theme name Dribbblish purple

**Comment by CharlieS1103** [comment]
Yeah i fixed this on my theme by changing the height value of the context menu and then setting overflow-y to scroll. You can do it yourself if you dont feel like waiting, but hopefully dribblish dude will fix it.

**Comment by khanhas** [comment]
Your spotify is ancient. Please upgrade Spotify to the lastest and try again.
