### ISSUE TITLE
Ziro theme sidebar has out-of-place buttons

### ISSUE THREAD

**Issue by ynavott** [morpheusthewhite/spicetify-themes#526]
**Describe the bug**
The sidebar buttons for "Create playlist", "Liked Songs", "Your Episodes" have overlapping icons and are out of place

**To Reproduce**
Apply Ziro theme with any color scheme.

**Screenshots**
![Ziro-purpledark-off](https://user-images.githubusercontent.com/48953594/132002851-d48de432-f6e7-4656-b6f1-d20d141ff06f.png)

**Logs**
```
vendor~xpui.js:1 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2656773)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2659055)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2091056
    at ka (https://xpui.app.spotify.com/vendor~xpui.js:29:2946534)
    at Ps (https://xpui.app.spotify.com/vendor~xpui.js:29:2970386)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3190652)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2916042)
    at Is (https://xpui.app.spotify.com/vendor~xpui.js:29:2970165)
    at ws (https://xpui.app.spotify.com/vendor~xpui.js:29:2954936)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2953858)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2916314
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3190652)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2916042)
    at yi (https://xpui.app.spotify.com/vendor~xpui.js:29:2916259)
    at vi (https://xpui.app.spotify.com/vendor~xpui.js:29:2916194)
    at As (https://xpui.app.spotify.com/vendor~xpui.js:29:2954357)
    at rl (https://xpui.app.spotify.com/vendor~xpui.js:29:2980770)
    at render (https://xpui.app.spotify.com/vendor~xpui.js:29:2983881)
    at https://xpui.app.spotify.com/xpui.js:1:1033162
(anonymous) @ vendor~xpui.js:1
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/service-worker.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/22.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-playlist.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Specifics (please complete the following information):**
 - OS: Windows 10
 - Spotify version 1.1.67.586.gbb5ef64e
 - Spicetify version 2.6.1
 - Theme name: Ziro

**Comment by schnensch0** [comment]
this happens because the css map isn't fully updated yet. i've pushed temporary fixes to [my repo](https://github.com/schnensch0/ziro), it should automatically fix itself when all the css mappings are done though.

**Comment by morpheusthewhite** [comment]
@ynavott check if the issue is solved
