### ISSUE TITLE
[Dribbblish] Icons dont show up in the sidebar

### ISSUE THREAD

**Issue by Alex62661** [morpheusthewhite/spicetify-themes#536]
**Describe the bug**
Icons do not show up neither on the siderbar or on the profile picture (even tho i dont have one)

**To Reproduce**
1. Open Spicetify
2. Load the dribbblish theme
3. Look at the sidebar and see no icons (the error)

**Expected behavior**
I expected the icons to be there but insted i only got text

**Screenshots**
![asdf](https://user-images.githubusercontent.com/90553315/132983856-f8d47f19-046d-468f-a907-075b920ff84f.PNG)

**Logs**

```console
vendor~xpui.js:1` MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2656773)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2659055)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2091056
    at ka (https://xpui.app.spotify.com/vendor~xpui.js:29:2946534)
    at Ps (https://xpui.app.spotify.com/vendor~xpui.js:29:2970386)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3190652)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2916042)
    at Is (https://xpui.app.spotify.com/vendor~xpui.js:29:2970165)
    at ws (https://xpui.app.spotify.com/vendor~xpui.js:29:2954936)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2953858)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2916314
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3190652)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2916042)
    at yi (https://xpui.app.spotify.com/vendor~xpui.js:29:2916259)
    at vi (https://xpui.app.spotify.com/vendor~xpui.js:29:2916194)
    at As (https://xpui.app.spotify.com/vendor~xpui.js:29:2954357)
    at rl (https://xpui.app.spotify.com/vendor~xpui.js:29:2980770)
    at render (https://xpui.app.spotify.com/vendor~xpui.js:29:2983881)
    at https://xpui.app.spotify.com/xpui.js:1:1033479
(anonymous) @ vendor~xpui.js:1
vendor~xpui.js:1 Uncaught TypeError: Cannot read property 'position' of null
    at Object.getProgress (spicetifyWrapper.js:30)
    at Dribbblish (dribbblish.js:172)
    at r (vendor~xpui.js:1)
sentry.io/api/114855/envelope/?sentry_key=de32132fc06e4b28965ecf25332c3a25&sentry_version=7:1 Failed to load resource: the server responded with a status of 429 (Too Many Requests)
sentry.io/api/114855/store/?sentry_key=de32132fc06e4b28965ecf25332c3a25&sentry_version=7:1 Failed to load resource: the server responded with a status of 429 (Too Many Requests)
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
pubads_impl_2021090701.js:6 [GPT] Invalid argument: PubAdsService.setRequestNonPersonalizedAds("0"). Valid values: 0,1.
(anonymous) @ pubads_impl_2021090701.js:6
pubads_impl_2021090701.js:6 [GPT] Invalid argument: PubadsService.setTagForUnderAgeOfConsent("0"). Valid values: 2,0,1.
(anonymous) @ pubads_impl_2021090701.js:6
21vendor~xpui.js:1 Error: SUB request to sp://player/v2/main?reverse_cap=2&future_cap=2 failed with exception 'Cannot read property 'offsetLeft' of null'
    at s.onSuccess (xpui.js:1)
    at onSuccess (xpui.js:1)
(anonymous) @ vendor~xpui.js:1
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-routes-homepage-takeover-ad.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-home.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/998.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/22.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-collection.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-collection-local-files.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-collection-songs.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/service-worker.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED

```

**Specifics (please complete the following information):**
 - OS: Windows 10
 - Spotify version 1.1.67.586.gbb5ef64e
 - Spicetify version: 2.2.2
 - Dribblish

**Comment by sTea-1th** [comment]
same here any work around yet? or just wait for the next update the?

**Comment by Alex62661** [comment]
nope, im still waiting for a dev to answer, ive switched to basic themes but even them dont work properly

**Comment by DaitiDay** [comment]
Seems like the new spotify update (1.1.68.628) has fixed the issue.

**Comment by Sqoler** [comment]
Problem is still not fixed...

**Comment by ZXSwire3** [comment]
I was having the same issue, but I just tried using the auto install in the README.md for windows, not sure if that's what fixed it, but after I did that it was the icons were back

**Comment by morpheusthewhite** [comment]
If you update spicetify to the latest version do you still experience it?

**Comment by DaitiDay** [comment]
Fixed on linux
