### ISSUE TITLE
Fluent Theme Window Control Bug

### ISSUE THREAD

**Issue by aayushbhatia06** [morpheusthewhite/spicetify-themes#545]
**Describe the bug**
When using the fluent theme (AWESOME work btw) and the  "--transparent-window-controls" command the Window controls not only still show but look very ugly. The three dot menu also shows up and also has a ugly color

**Screenshots**
<img width="1280" alt="Screenshot 2021-09-26 131558" src="https://user-images.githubusercontent.com/62324210/134798908-00e527b2-d7a4-4edb-b42b-c5272a677d1d.png">

![image](https://user-images.githubusercontent.com/62324210/134798927-4c420066-8053-4c3c-b1c4-41c4025dc192.png)

**Logs**
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2353172)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2355454)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2048746
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2595327)
    at As (https://xpui.app.spotify.com/vendor~xpui.js:29:2619179)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2793496)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564835)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2618958)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2603729)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2602651)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2565107
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2793496)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564835)
    at yi (https://xpui.app.spotify.com/vendor~xpui.js:29:2565052)
    at vi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564987)
    at Es (https://xpui.app.spotify.com/vendor~xpui.js:29:2603150)
    at rl (https://xpui.app.spotify.com/vendor~xpui.js:29:2629563)
    at render (https://xpui.app.spotify.com/vendor~xpui.js:29:2632674)
    at https://xpui.app.spotify.com/xpui.js:1:1033981
(anonymous) @ vendor~xpui.js:1
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/service-worker.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/22.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-collection-songs.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED

**Specifics (please complete the following information):**
 - OS: Windows 11
 - Spotify version [e.g. 1.1.10.546.ge08ef575]
 - Spicetify version: Spotify for Windows 1.1.68.632.g2b11de83
 - Theme name: Fluent UI (Light)

**Comment by morpheusthewhite** [comment]
Can you try to use the alternatives (https://github.com/morpheusthewhite/spicetify-themes/tree/master/_Extra/SpotifyNoControl#alternatives)?

**Comment by aayushbhatia06** [comment]
> Can you try to use the alternatives (https://github.com/morpheusthewhite/spicetify-themes/tree/master/_Extra/SpotifyNoControl#alternatives)?

Tried the executable. Same result i.e No effect - Window controls visible and in the weird color shown in the orignal screenshot

**Comment by morpheusthewhite** [comment]
Do you experience the same problem if using other themes?

**Comment by Skyline404** [comment]
Can confirm SpotifyNoControl no longer works

**Comment by morpheusthewhite** [comment]
Let's track this issue [here](https://github.com/morpheusthewhite/spicetify-themes/issues/546)
