### ISSUE TITLE
[Dribbblish] Sidebar folders invisible

### ISSUE THREAD

**Issue by verafieduser** [morpheusthewhite/spicetify-themes#616]
**Describe the bug**
Folders aren't showing up in the sidebar. I have tried both the automatic install and the manual. I have also tried reinstalling spicetify. Am also using fullAppDisplay and popupLyrics, do not know if the bug could be due to some interaction.

**To Reproduce**
1. Open Spotify
2. Playlist folder names visible for a fraction of a section before...
3. They disappear, showing what is visible in the screenshot below.

**Expected behavior**
I expect folder names to be visible.

**Screenshots**
![bild](https://user-images.githubusercontent.com/70537481/142760094-d34c8dea-7f39-4eb5-b6b2-e8dba96f0cf5.png)

**Logs**
![bild](https://user-images.githubusercontent.com/70537481/142760502-fdaeca10-c34d-40e2-97a1-718617d3be27.png)

```console
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
3fluent.js:77 Uncaught TypeError: Cannot read properties of undefined (reading 'Translations')
    at fluent.js:77
(anonymous) @ fluent.js:77
setInterval (async)
fluent @ fluent.js:76
(anonymous) @ fluent.js:100
vendor~xpui.js:29 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2621881)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2624465)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2254849
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2859683)
    at Is (https://xpui.app.spotify.com/vendor~xpui.js:29:2883415)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3096998)
    at gr (https://xpui.app.spotify.com/vendor~xpui.js:29:2829219)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2883194)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2868073)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2866995)
c @ vendor~xpui.js:29
o.addListener @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Pa @ vendor~xpui.js:29
Is @ vendor~xpui.js:29
t.unstable_runWithPriority @ vendor~xpui.js:29
gr @ vendor~xpui.js:29
ks @ vendor~xpui.js:29
Os @ vendor~xpui.js:29
vs @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
t.unstable_runWithPriority @ vendor~xpui.js:29
gr @ vendor~xpui.js:29
yr @ vendor~xpui.js:29
vr @ vendor~xpui.js:29
Ss @ vendor~xpui.js:29
il @ vendor~xpui.js:29
render @ vendor~xpui.js:29
(anonymous) @ xpui.js:1
async function (async)
(anonymous) @ xpui.js:1
36195 @ xpui.js:1
s @ xpui.js:1
(anonymous) @ xpui.js:1
s.O @ xpui.js:1
(anonymous) @ xpui.js:1
(anonymous) @ xpui.js:1
fluentui-system-icons/ic_fluent_pause_16_filled.svg:1 GET https://xpui.app.spotify.com/fluentui-system-icons/ic_fluent_pause_16_filled.svg net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/696.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-folder.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
fluentui-system-icons/ic_fluent_folder_24_filled.svg:1 GET https://xpui.app.spotify.com/fluentui-system-icons/ic_fluent_folder_24_filled.svg net::ERR_NAME_NOT_RESOLVED
images/tracklist-row-song-fallback.svg:1 GET https://xpui.app.spotify.com/images/tracklist-row-song-fallback.svg net::ERR_NAME_NOT_RESOLVED
Image (async)
loadPlaylistImage @ dribbblish.js:62
(anonymous) @ dribbblish.js:83
waitForElement @ dribbblish.js:31
setTimeout (async)
waitForElement @ dribbblish.js:33
setTimeout (async)
waitForElement @ dribbblish.js:33
(anonymous) @ dribbblish.js:37
fluentui-system-icons/ic_fluent_play_24_filled.svg:1 GET https://xpui.app.spotify.com/fluentui-system-icons/ic_fluent_play_24_filled.svg net::ERR_NAME_NOT_RESOLVED
```

**Specifics (please complete the following information):**
 - OS: Windows 10 (19043.1348)
 - Spotify version Spotify for Windows 1.1.72.439.gc253025e
 - Spicetify version 2.8.2
 - Theme name: Dribbblish

**Comment by verafieduser** [comment]
Okay I was being stupid and had fluent activated at the same time. My apologies!
